export const relativePath = {
  root: "/",
  login: "/login",
  changePassword: "/change-password",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  home: {
    main: "/home",
    dashboard: "dashboard",
    notifications: "notifications",
    ai: "ai",
    members: {
      main: "members",
      mainNew: "/home/members",
      manage: "members/manage-member",
      details: "members/:id",
      info: "members/:id",
    },
    membership: {
      main: "membership",
      churchDirectory: "church-directory",
      departments: {
        main: "departments-and-ministries",
        details: "departments-and-ministries/:id",
      },
      analytics: "analytics",
      management: {
        main: "membership-management",
        memberConfirmation: "member-confirmation",
        visitorToMembership: "visitor-to-membership",
        soulwonToMembership: "soulwon-to-membership",
      },
    },
    visitors: {
      main: "visitors",
      details: "visitors/visitor/:visitorId",
    },
    events: {
      main: "events",
      manage: "manage-event",
      view: "view-event",
    },
    reports: {
      main: "reports",
      eventReports: "reports/event-reports",
      eventReportDetails: "reports/event-reports/:id",
    },
    attendance: {
      main: "church-attendance",
      eventAttendance: "event-attendance",
      analytics: "analytics",
    },
    assets: {
      main: "assets",
      manage: "assets/manage-asset",
    },
    users: {
      main: "users",
      details: "users/:id/info",
    },
    ministrySchool: {
      main: "ministry-school",
      program: "programs",
      topic: "topic/:topicId",
      cohort: "cohort/:id",
      class: "class/:id",
      student: "student/:id",
      instructorPortal: "instructor-portal",
      instructorCohort: ":programId/cohort",
      instructorAssMan: ":programId/cohort/:cohortId",
      instructorGradingPanel: ":programId/cohort/:cohortId/grades/:topicId",
      certificate: "ministry-school/programs/cohort/class/student/certificate",
    },
    settings: {
      main: "settings",
      general: "settings",
      accessRights: "settings/access-rights",
      manageAccess: "settings/access-rights/manage-access",
    },
    lifeCenter: {
      main: "life-centers",
      detail: "life-center/:id",
    },
    marketPlace: {
      main: "market-place",
      details: "market-place/:id",
      addProduct: "market-place/:marketId/create-product",
      editProduct: "market-place/:marketId/edit-product/:productId",
    },
    fallback: "*",
  },
  out: {
    main: "/out",
    programs: {
      main: "/out/programs",
      details: "/out/programs/:name",
      apply: "/out/programs/:name/apply",
    },
    registerMember: "/out/register-member",
    registerEvent: "/out/events/register-event",
  },
  programs: {
    details: "/programs/:name",
    apply: "/programs/:name/apply",
  },
  member: {
    main: "/member",
    dashboard: "/member/dashboard",
    profile: "/member/profile",
    notifications: "/member/notifications",
    market: "/member/market/",
    productDetails: "/member/market/product/:id",
    cart: "/member/market/carts",
    checkOut: "/member/market/check-out",
    orders: "/member/market/orders",
    verify_payment: "/member/market/verify_payment/member",
    lifeCenter: "/member/life-center",
    schoolOfMinistries: {
      main: "school-of-ministries",
      allPrograms: "school-of-ministries/programs",
      myClass: "school-of-ministries/my-class",
      myEnrolledPrograms: "school-of-ministries/programs/my-enrolled-programs",
      programDetails: "school-of-ministries/programs/my-enrolled-programs/:programId",
      instructorPortal: "school-of-ministries/programs/instructor-portal",
      instructorCohort: ":programId/cohort",
      instructorAssMan: ":programId/cohort/:cohortId",
      InstructorGradingPanel:":programId/cohort/:cohortId/grades/:topicId"
    },
    appointments: "/member/appointments",
  },
  registerMember: "/register-member",
  registerEvent: "/events/register-event",
};
