import type { NotificationPriority } from "@/utils/api/notifications/interfaces";

export interface NotificationActionDefinition {
  type: string;
  entityType: string;
  description: string;
  actionUrlTemplate: string;
  defaultPriority: NotificationPriority;
  toastForHighPriorityOnly: boolean;
}

export const NOTIFICATION_ACTION_REGISTRY: NotificationActionDefinition[] = [
  {
    type: "requisition.submitted",
    entityType: "requisition",
    description: "Requisition submitted and routed to first approver.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "requisition.step_advanced",
    entityType: "requisition",
    description: "Requisition moved to next approval step.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "requisition.final_approved",
    entityType: "requisition",
    description: "Requisition finally approved.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "requisition.final_rejected",
    entityType: "requisition",
    description: "Requisition finally rejected.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "requisition.comment_added",
    entityType: "requisition",
    description: "Approval-stage comment added to requisition.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "appointment.booked",
    entityType: "appointment",
    description: "Appointment booked for assigned staff.",
    actionUrlTemplate: "/home/appointments",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "appointment.status_changed",
    entityType: "appointment",
    description: "Appointment status changed (confirmed/cancelled/pending).",
    actionUrlTemplate: "/member/appointments",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "follow_up.assigned",
    entityType: "follow_up",
    description: "Follow-up assigned to a member.",
    actionUrlTemplate: "/home/visitors/visitor/{visitorId}",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "follow_up.due",
    entityType: "follow_up",
    description: "Follow-up is due.",
    actionUrlTemplate: "/home/visitors/visitor/{visitorId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "follow_up.overdue",
    entityType: "follow_up",
    description: "Follow-up is overdue.",
    actionUrlTemplate: "/home/visitors/visitor/{visitorId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "event.updated",
    entityType: "event",
    description: "Event details updated for registered users.",
    actionUrlTemplate: "/events/register-event?event_id={entityId}",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "event.cancelled",
    entityType: "event",
    description: "Event cancelled.",
    actionUrlTemplate: "/events/register-event?event_id={entityId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "event.registration_success",
    entityType: "event_registration",
    description: "Event registration successful.",
    actionUrlTemplate: "/events/register-event?event_id={entityId}",
    defaultPriority: "LOW",
    toastForHighPriorityOnly: true,
  },
  {
    type: "order.payment_success",
    entityType: "order",
    description: "Order payment succeeded.",
    actionUrlTemplate: "/member/market/orders",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "order.payment_failed",
    entityType: "order",
    description: "Order payment failed.",
    actionUrlTemplate: "/member/market/orders",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "delivery.status_changed",
    entityType: "delivery",
    description: "Delivery status changed (shipped/delivered/cancelled).",
    actionUrlTemplate: "/member/market/orders",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: false,
  },
  {
    type: "event_report.submitted_for_final_approval",
    entityType: "event_report",
    description: "Event report submitted for final approval.",
    actionUrlTemplate: "/home/reports/event-reports",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "event_report.final_approved",
    entityType: "event_report",
    description: "Event report finally approved.",
    actionUrlTemplate: "/home/reports/event-reports",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "event_report.final_rejected",
    entityType: "event_report",
    description: "Event report finally rejected.",
    actionUrlTemplate: "/home/reports/event-reports",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "financial.approval_requested",
    entityType: "financial",
    description: "Financial record submitted for approver review.",
    actionUrlTemplate: "/home/finance/{entityId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "financial.approved",
    entityType: "financial",
    description: "Financial record finally approved.",
    actionUrlTemplate: "/home/finance/{entityId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: false,
  },
  {
    type: "system.job_failed",
    entityType: "system_job",
    description: "Critical system/reconciliation/notification job failed.",
    actionUrlTemplate: "/home/dashboard",
    defaultPriority: "CRITICAL",
    toastForHighPriorityOnly: true,
  },
  {
    type: "requisition.approval_reminder",
    entityType: "requisition",
    description: "Added: pending approver reminder for stale requisitions.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "requisition.escalated",
    entityType: "requisition",
    description: "Added: approval escalation after SLA breach.",
    actionUrlTemplate: "/home/requests/{encodedRequisitionId}",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "appointment.reminder_24h",
    entityType: "appointment",
    description: "Added: appointment reminder 24h before schedule.",
    actionUrlTemplate: "/member/appointments",
    defaultPriority: "LOW",
    toastForHighPriorityOnly: true,
  },
  {
    type: "appointment.no_show_recorded",
    entityType: "appointment",
    description: "Added: appointment marked as no-show.",
    actionUrlTemplate: "/home/appointments",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: true,
  },
  {
    type: "follow_up.commented",
    entityType: "follow_up",
    description: "Added: comment added on assigned follow-up.",
    actionUrlTemplate: "/home/visitors/visitor/{visitorId}",
    defaultPriority: "LOW",
    toastForHighPriorityOnly: true,
  },
  {
    type: "event.reminder_24h",
    entityType: "event",
    description: "Added: reminder sent to registered users 24h before event.",
    actionUrlTemplate: "/home/events",
    defaultPriority: "LOW",
    toastForHighPriorityOnly: true,
  },
  {
    type: "order.refund_initiated",
    entityType: "order",
    description: "Added: refund initiated for order.",
    actionUrlTemplate: "/member/market/orders",
    defaultPriority: "MEDIUM",
    toastForHighPriorityOnly: true,
  },
  {
    type: "delivery.exception",
    entityType: "delivery",
    description: "Added: delivery exception requires owner action.",
    actionUrlTemplate: "/member/market/orders",
    defaultPriority: "HIGH",
    toastForHighPriorityOnly: true,
  },
  {
    type: "system.notification_delivery_failed",
    entityType: "system_job",
    description: "Added: notification delivery pipeline failure for admins.",
    actionUrlTemplate: "/home/notifications",
    defaultPriority: "CRITICAL",
    toastForHighPriorityOnly: true,
  },
];

const notificationActionDefinitionMap = new Map(
  NOTIFICATION_ACTION_REGISTRY.map((definition) => [definition.type, definition]),
);

export const getNotificationActionDefinition = (
  type: string
): NotificationActionDefinition | null =>
  notificationActionDefinitionMap.get(type) || null;
