name: Prevent Branch Reuse

on:
  pull_request:
    types:
      - opened

jobs:
  prevent-branch-reuse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your repository

      - name: Check if branch was merged
        run: |
          BRANCH="reuseableBranches"
          if git branch --merged main | grep "${BRANCH}"; then
            echo "This branch has already been merged. Create a new branch for your changes."
            exit 1
          else
            echo "Branch not merged. Workflow can proceed."
          fi
