name: Prevent Branch Reuse

on:
  pull_request:
    types:
      - opened

jobs:
  prevent-branch-reuse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if branch was merged
        run: |
          BRANCH="reuseableBranches"
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          
          if git branch --merged $DEFAULT_BRANCH | grep "${BRANCH}"; then
            echo "This branch has already been merged. Create a new branch for your changes."
            exit 1
          else
            echo "Branch not merged. Workflow can proceed."
          fi

